### ISSUE TITLE
80 pin VAG connector breakout board

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1676]
We do not know anyone with this connector but we have forum inquiry https://rusefi.com/forum/viewtopic.php?f=4&t=1818
 
I have these connectors new for sale so selling with connector would be a nice publicity item

**Comment by jwrb** [comment]
Models and pin latouy for this connection can be found on the TE Connectivity website:

https://www.te.com/usa-en/product-8-1393476-0.html

**Comment by jwrb** [comment]
I already brought the connector into KiCad to start making a PCB, but it's been a few years since I touched any PCB Cad software so I'm a little lost.

The files I used are attached.
[8-1393476-0_KiCad Libraries.zip](https://github.com/rusefi/rusefi/files/5037703/8-1393476-0_KiCad.Libraries.zip)

<img width="1001" alt="Screen Shot 2020-08-06 at 20 57 58" src="https://user-images.githubusercontent.com/1545757/89576776-a1513780-d827-11ea-8c82-4a6937082a11.png">

**Comment by rusefillc** [comment]
@jwrb I've pushed both files into rusEFI library repository

Any progress on the adapter board?

**Comment by jwrb** [comment]
@rusefillc It's been years since I dabbled with PCB design. Still working my way through it. Would be very nice to have a layout.

I'd like to get it designed so I can have some PCB's made for my own builds.

**Comment by rusefillc** [comment]
Aborting

**Comment by jwrb** [comment]
@rusefillc 
I've gotten in contact with a couple of PCB designers regarding this. I'll be commisioning a PCB layout for this connector.

Once complete, I will add it to the repo, and submit a PR.

Thanks

**Comment by rusefillc** [comment]
I've actually already paid someone to make a breakout board - just pushed, see associated commit. 

Between you contributing the footprint I have to make the board public but I will probably not publish official gerbers for this board.

**Comment by jwrb** [comment]
> I've actually already paid someone to make a breakout board - just pushed, see associated commit.
> 
> Between you contributing the footprint I have to make the board public but I will probably not publish official gerbers for this board.

Oh great! That's fab news! I'll have to see about sorting a few boards for my personal use!
Thank you! :)
