### ISSUE TITLE
Nissan Altima: something clicks on "Burn"

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3140]
Nissan Almera with hellen

something clicks on Burn maybe FSIO ETB relay? #3139

**Comment by mck1117** [comment]
It's probably the fan relay, if you have one.  During the flash, sensors go invalid since the ADC thread gets blocked, so when flash completes, there's a narrow window when things like relays might update without the having updated yet, so they briefly see invalid coolant temperature or something (in which case, fans turn on!)

**Comment by mck1117** [comment]
#3145

**Comment by rusefillc** [comment]
I think fan relay is not configured nor soldered

Xterra has CAN fan no idea what Almera does, this ticket is about Almera from yesterday

**Comment by rusefillc** [comment]
we have ``burnconfig``

**Comment by rusefillc** [comment]
weird dead ticket
