### ISSUE TITLE
FEATURE REQ: secondary delayed spark

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#327]
http://rusefi.com/forum/viewtopic.php?f=5&t=1112 mentions a 3 cylinder engine with 6 sparks. We need a feature to produce secodary spark using secondary channel based on a constact degree offset (constant degree offset would be different time delay based on RPM)

Reported by: rusefi

**Comment by smonette-jive** [comment]
I had a discussion with Ray Barton about secondary spark on hemi engines since they new hemi engines have dual spark plugs per cylinder. According to Ray, we're better off sparking both plugs at the same time than setting them up with a delayed secondary spark. The secondary spark will not generate more power.

At high speed, I think you won't have enough time to charge the coil to ignite the secondary spark within the next 15 degrees (0.0003s @ 7,000 RPM).

**Comment by mck1117** [comment]
we have this now, both trailing spark outputs (second coil) and multispark (same coil, multiple sparks per ignition) are supported
