### ISSUE TITLE
GHA: submodules: recursive

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3494]
Do we really need ``submodules: recursive`` or can we save the planet by not?

![image](https://user-images.githubusercontent.com/48498823/140631378-e8a51661-7539-4ea8-bf6d-184b1a1ef407.png)

**Comment by mck1117** [comment]
Idk, see what happens if you disable recursive? I think it's fine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: rusefillc ***@***.***>
Sent: Saturday, November 6, 2021 8:32:57 PM
To: rusefi/rusefi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rusefi/rusefi] GHA: submodules: recursive (Issue #3494)


Do we really need submodules: recursive or can we save the planet by not?

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48498823%2F140631378-e8a51661-7539-4ea8-bf6d-184b1a1ef407.png&data=04%7C01%7C%7Cf1874944f2d84438ec9e08d9a19f4b24%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637718527803277315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b3PTFTyK8oYTYwk0XVPh5gYao1FWVgEsRYq7HGPdBZg%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frusefi%2Frusefi%2Fissues%2F3494&data=04%7C01%7C%7Cf1874944f2d84438ec9e08d9a19f4b24%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637718527803277315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8ctdFtIXaMJVOMXdZJXJouJS%2FS7ME6seqsMh%2BWaJJoU%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAEKXPV5CER5O6CJWUDI2KDUKX6PTANCNFSM5HQKMVLA&data=04%7C01%7C%7Cf1874944f2d84438ec9e08d9a19f4b24%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637718527803287278%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fRi2vQi4tXLKYkPN4LNwlFuTVRYlPQVz0jnD819uL18%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf1874944f2d84438ec9e08d9a19f4b24%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637718527803287278%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y8nQmVUtgyzBxU3hcXEkmFOoYJjHkoEgRbCt0zZ1wpU%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cf1874944f2d84438ec9e08d9a19f4b24%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637718527803297255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uP6tuzRm1NVAsqLc%2F3zpxMTGJA7qlvZRwXGeBdTuSd8%3D&reserved=0>.
