### ISSUE TITLE
logging of live data structs was: data points

### ISSUE THREAD

**Issue by mmatousek89** [rusefi/rusefi#3614]
@mmatousek89 reports

Why so many channels are hidden in debug?
Can we have all of them logged all time?

@rusefillc response
live data structures should be merged with existing outputs for TS, TS should see all live data structures as yet another output channel and should be able to log either of it

implementation detail
``
FragmentEntry
``

**Comment by mck1117** [comment]
examples?

**Comment by mmatousek89** [comment]
tps diff
wastegate dc from table
etb pri/sec diff
.... and 70others

**Comment by rusefillc** [comment]
@mmatousek89 historically we were concerned about RAM and traffic

At this point I believe we can afford to have way more gauges not as debug mode.

instead of asking for "70 others" it would be best to ask specifically for the ones you need this week/next week to get results quicker in a more focused way

**Comment by rusefillc** [comment]
Depends on #197

**Comment by rusefillc** [comment]
@racer-coder can you help? that would mean finishing #197

**Comment by racer-coder** [comment]
I agree that everything should be exposed.  I think it comes down to philosophical "how should the core of the software operate", which I'm kinda trying to tackle partly with rethinking how tables work.

Using Motec M600/800/etc software as an example,
1. First you configure all the inputs.  Inputs can be direct connected sensors or received over canbus/expansion blocks.
2. Engine management goes and computes a bunch of intermediaries.  Estimated air mass, VE after compensations, Fuel required, injector duration for fuel required, etc
3. ALL of these variables - inputs + computed variables - are available to be logged, transmitted over CAN, or to be used as inputs into other tables for more computation
4. Outputs (solenoids etc) are based on the variables + some logic

Since there are so many variables, you need a tree view to fit them so you aren't scrolling forever through some giant list.  Link actually lets you type a search phrase in the dialog box that selects variables.

So yes, there should be a centralized place to describe all variables - whether inputs or not, including units, precision, scale, # bytes, etc.  Then all the logic in the software should refer to this centralized variable list.

I think we kinda already have this for sensors, but it should be extended to everything else too.

As for logging them "all the time" or not, that comes down to how much storage we have, but I assume the MCU is powerful enough and I assume we use an external microSD card so we should have plenty of bandwidth and storage space to log everything.  Link ECU lets you select which channels you log and what refresh rate you choose for each of them.

**Comment by rusefillc** [comment]
@racer-coder I think we are pretty much on the same page here

specifically the whole "live data" approach with machine readable state for all controllers seems like a way to implement. In my opinion we shall extend current flat real OutputsChannels where we COPY data from model into OutputsChannels with a synthetic/virtual OutputsChannels which is composed of list of live data models under the hood

**Comment by rusefillc** [comment]
introduces #3633

**Comment by mck1117** [comment]
> linked list of memory regions under the hood presented to TS as one continues buffer

This doesn't need to be a linked list - we can C++ compile-time-zero-cost-list this like we do with `engineModules`

**Comment by rusefillc** [comment]
Right, I guess we can but that would impost additional constraints and conventions. Conditional compilation would get trickier, we would need to make sure that no fields are added with inheritance etc etc?

**Comment by nmschulte** [comment]
should the wiki page https://github.com/rusefi/rusefi/wiki/Debug-Mode (https://www.rusefi.com/s/debugmode) and related https://github.com/rusefi/rusefi/wiki/Debug-Fields be sunset now or does this need more burn-in/effort?

**Comment by mi-hol** [comment]
> should the wiki page https://github.com/rusefi/rusefi/wiki/Debug-Mode (https://www.rusefi.com/s/debugmode) and related https://github.com/rusefi/rusefi/wiki/Debug-Fields be sunset now or does this need more burn-in/effort?

@rusefillc in case the question is answered I'd be happy to update wiki
