### ISSUE TITLE
Do we push config on any change now?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3647]
https://github.com/rusefi/rusefi/commit/7a7a89ae7841ccbef912d9f57d388c71aab1fb28 has caused https://github.com/rusefi/rusefi/commit/c9aa40293ca292e80fa10ce2108c71de01d20588 ?

**Comment by rusefillc** [comment]
Introduces by #3639 ?

**Comment by mck1117** [comment]
OK I know what's happening.  `gen_config.sh` generates all files for every board in sequence, including `Fields.java`, for example.  Since `Fields.java` contains some per-board content, it gets changed by every board that `gen_config.sh` generates.  Over the course of a build there is no *net* change to `Fields.java`, but every board generated edits it, so LazyFile is actually doing the right thing.
