### ISSUE TITLE
Remove/make injector duty limit configurable

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4798]
I have customers complaining about random cuts, after  seeing a VIDEO of injector duty, it goes over 100%, triggering the duty limit. Can we have an option that when duty is >96%, the injector outputs go static(stuck to ground without closing).

If the drivers can support this, I believe this is an easy way to let them lean out and blow their shit up, which is not our fault since the ECU is reporting that it is the current behavior; maybe choose between current behavior and this

**Comment by rusefillc** [comment]
I wonder if those users are running a recent version with https://github.com/rusefi/rusefi/pull/4592 improvement

the https://github.com/rusefi/rusefi/pull/4592 with nice indicators was supposed to have helped?

**Comment by ElDominio** [comment]
Indicators work, but people swear their fuel system is enough and the ECU is holding them back

**Comment by ElDominio** [comment]
This is very problematic in cars where transient goes over for a split second and the limit stays engaged with the throttle at WOT (fuel is cut until car is no longer WOT). This is happening with a drift car when the user stabs the throttle close to rev limit and transient fueling makes duty go over 100% for a split second. Is there any progress on this? @mck1117 @rusefillc

**Comment by rusefillc** [comment]
transient and short term 100% duty looks like a great argument to remove the limit

**Comment by mck1117** [comment]
> transient and short term 100% duty looks like a great argument to remove the limit

there has been some extensive offline discussion about this - something like only engaging the limiter after some period of time is probably the right solution. Allow very brief over 100% moments, but still cut if you're far over 100% for a "long time".

It also needs some fixes to injection scheduling to happen first.

**Comment by rusefillc** [comment]
> It also needs some fixes to injection scheduling to happen first.

absolutely, things would break if condition is just removed

**Comment by ElDominio** [comment]
Again with my theorycrafts, couldn't the fueling algorithm just "lock" when injector duty reaches say 96%, stop calculating additional fuel and justkeep the duty cycle locked at 96%, while UI reports unreal duty? (tag: Norman says)

**Comment by mck1117** [comment]
Even more evil is that we could display actual duty * 1.042 so that 96% duty displays as 100% 😈

But we shouldn't do that, there are real solutions here too.

**Comment by ElDominio** [comment]
please jesus do something about this, every time i run into this at the dyno i waste valuable dyno time

**Comment by rusefillc** [comment]
@ElDominio my estimation is that doing something is relatively expensive. It's NOT one line change, proper transition to 100% and back would require effort. If not done properly there is a chance to mess things up badly.

**Comment by ElDominio** [comment]
Snip of me complaining on Slack
![image](https://user-images.githubusercontent.com/5685108/229304635-5cd50735-70c9-4773-aa8f-909989f44e64.png)

**Comment by ElDominio** [comment]
a big warning in TS somewhere that says this limit has been reached would be swell, like the coolant temp warning that blacks out the entire screen. how easy to implement that?

**Comment by ElDominio** [comment]
This just boned me in a parallel ECU.

Duty limit makes the engine go lean if the user requests more fuel than 100%, where the injectors controlled are supplemental (not the main ones), and it makes it go extremely lean.

**Comment by mck1117** [comment]
add that to the list of reasons a piggyback ecu is a hack

**Comment by ElDominio** [comment]
As true as that might be

People see videos like this
https://youtu.be/1mmhkPTe6F0

And buy an ECU, and this time around they bought it from me. I was tasked with giving them customer support (since the guy was tuning it on his own) because of this and ran into the issue.

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/commit/6ff8e67acd4175ca22271d6472b875e8b1c1c1c4

**Comment by davepmo** [comment]
Hi Guys,
I'm a new user, so bear with me.  I have a Proteus V7 board running on an PNP adapter board that I made.  Application is an Arctic cat  1100 turbo snowmobile with factory staged injectors.  FYI, Thanks for adding staged injectors, this is working.  However, I'm running into this 100% duty cycle issue also.  I see in the forums this was discussed and marked as completed on Sept 10, 2023 but it's unclear what the fix was, or if there is some interaction with the staged injectors going 100%.

In tunerstudio the settings I see are maximum allowed duty cycle (I set to 110% in an attempt to get around this), and there is a timeout value which will only allow a max of 5 seconds.  Sure enough, if I go over 5 seconds it shuts them down. 

We race a "stock" class on stock turbo and fuel system.  So the wastegate is bolted shut for max boost and we run both sets of injectors at 100% all day long, and have been for years.  Everyone is. 

I need to be able to run both sets of injectors at 100% with no limitations.  Any suggestions on where to start to resolve this are welcome.

Thanks a lot,
Dave.
 
I see the code below, do I need to edit this and recompile to get around this?  Is there a better workaround?

	// Cut at 110% instantly
	engineConfiguration->maxInjectorDutyInstant = 110;
	// Cut at 96% after 0.5 second
	engineConfiguration->maxInjectorDutySustained = 96;
	engineConfiguration->maxInjectorDutySustainedTimeout = 0.5f;

**Comment by ElDominio** [comment]
What is your calculated injector dc while running?

**Comment by Modauser** [comment]
Hello ElDominio,
Thanks for the reply.  Here are more details:

I designed an engine simulator pcb and some software where I simulate the engine, and the software measures the injector pulse widths and timing at each load point from the OEM ECU at defined conditions.  So I have a full map of what the OEM ECU is doing, and I'm backing in the VE table in tunerstudio so that the injector pulse widths match at each load point OEM to Proteus.  I also am able to measure temp compensation, timing, and accelerator pump multiplier tables the same way.  

I've done this before many times and it works great, I have an almost complete copy of the OEM map into a standalone when done, and it only takes an hour or so to derive the VE load tables in a standalone, it's that automated.  The engine will run great and only needs minor tweaking on the dyno then in the wild afterwards.  FYI, I've tried to use this info to calc VE, but there are too many factors to get it dead on, turns out it is just faster to tweak the VE table by hand to match outputs OEM to standalone. 

This OEM map runs 100% in 10 or so load cells under max boost.

To specifically answer your question,   I have it set so it's trying to do 100%. I have not experimented with running slightly under, but I need all the fuel I can get at these load points.   I can understand if I had the VE table so it was commanding 200% duty cycle, it's not (I'll double check this when I get home).  I looked in the forums and found this was an issue, so I thought it might be faster asking for some help.   

 I just need some guidance so I can run 100% duty cycle without timing out.

Thanks again for the quick reply.  Any suggestions?
