### ISSUE TITLE
re-enable f407-discovery

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4858]
Somewhere in a dark dark house there is a dark basement
in the dark basement there is a dark closet
in the dark closet there is a pink f407-discovery HW CI discovery

**Comment by mck1117** [comment]
> pink

pink?

**Comment by rusefillc** [comment]
@mck1117

**Comment by rusefillc** [comment]
@mck1117 please blink if any aliens are not letting you into your basement

**Comment by mck1117** [comment]
something has happened in the category of "the USB card used for passthrough in to a VM on my server has died", but unclear exactly what

I'm in the process of shuffling some computers around, so I'm going to move f4 discovery CI to a real physical PC instead of running in a VM, so that hopefully USB is a bit more reliable.
