### ISSUE TITLE
getDigital only works for 4 specific pins. Can it be made to work with generic digital pins?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4861]
LUA can grab analog inputs, but pins declared as digital don't show in the LUA Analog Inputs (as they shouldn't), but I wanted to grab a switch state from LUA to do stuff. How can I do this?

**Comment by rusefillc** [comment]
At the moment we do not have this

We have not relevant https://github.com/rusefi/rusefi/wiki/Lua-Scripting#getdigitalindex

We have horrible option https://github.com/rusefi/rusefi/wiki/Lua-Scripting#readpinpinname which would be ugly

**Comment by ElDominio** [comment]
Nope sorry

**Comment by andreika-git** [comment]
We have at least three options IMHO:

1) use the existing getDigital(0..7) function and the new "Lua Digital Inputs" config dialog - and thus break compatibility with current getDigital() implementation which returns the state of 4 pre-defined inputs (clutch up/down, break pedal and AC button)

2) use the existing getDigital(4..11) function - but leave the first 4 indices as reserved for existing pre-defined inputs, and rename the added configurable aux inputs to "Digital #4"..."Digital #11", in order to support both old and new behavior.

3) add a new lua function getAuxDigital(0..7) similar to existing getAuxAnalog(), and maybe rename TS dialog to "Lua Aux Digital Inputs" (we already have a name inconsistency with 'aux' word for analog inputs)?

@ElDominio @rusefillc Can you please decide which one is better?

**Comment by rusefillc** [comment]
Let's go with option 3

**Comment by rusefillc** [comment]
@andreika-git please update Lua-Scripting wiki page?

**Comment by rusefillc** [comment]
@ElDominio seems to work
