### ISSUE TITLE
WA HW CI up monitor

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5168]
It looks like proteus HW CI is offline or hanging

A week ago it was discovery

How can we have computers poke @mck1117 instead of me poking @mck1117 ?

**Comment by FDSoftware** [comment]
For this we can use portainer-ce since GH runners run inside docker, portainer allows you to connect to remote docker instances and manage the containers or start a console within it
https://docs.portainer.io/start/install-ce

example connecting to my own docker instance:
![image](https://github.com/user-attachments/assets/0ba26076-9ad1-4869-96f0-5fac997f2d28)![image](https://github.com/user-attachments/assets/b858bc41-3393-46e6-8d66-b03754ead8ce)

The only problem with Portainer is that it leaves out the most sporadic maintenance (updating the host OS, checking the status of the USB ports, etc.), for that I found Rundeck, I never tried it but in the documentation it shows how to create actions that run bash commands on remote servers

https://docs.rundeck.com/docs/learning/howto/ssh-on-linux-nodes.html

**Comment by mck1117** [comment]
> How can we have computers poke @mck1117 instead of me poking @mck1117 ?

Those resources have been reallocated to another project.
