### ISSUE TITLE
I2C Baro problems

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5264]
![image](https://user-images.githubusercontent.com/5685108/235380036-e07f0585-6e70-4248-bb29-baed4ffb8d8b.png)

It reads 74kpa on a 2chan revE, and this shifts actual MAP to the same value. I cannot disable the SCL/SDA pins, and changing calibration does nothing.

**Comment by rusefillc** [comment]
@ElDominio we have at least three issues here
* calibration UI should be disabled when we use I2C since I2C does not use calibration
* we have validity check
```
	if (kilopascal > 120 || kilopascal < 50) {
		return unexpected;
	}
```
and that check does not seem to be enough in case of (your) breakage
* open question what's wrong with your unit. Please try your 4chanG those have same baro. my 2chanE reads 99KPa
* i guess it should be possible to disable I2C baro as a workaround for your issue

**Comment by rusefillc** [comment]
@ElDominio please confirm power cycle after change from analog baro into i2c baro?

**Comment by ElDominio** [comment]
User is dumb please close
