### ISSUE TITLE
openblt via CAN

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6043]
So many openblt changes recently can we get 2chan and small-can-board firmware upload to work via OpenBLT CAN?

Not to be confused with ST-CAN https://github.com/rusefi/rusefi/issues/5882

**Comment by andreika-git** [comment]
I've tested the possibility to flash firmware via ST Bootloader on CAN2 using STLinkv3 as it is useful to be able to flash blank chips from the factory via CAN.

TLDR; Interim results are disappointing. So far I haven't been able to get it to work...

Setup:
- 2chan rev.F (mega-mcu144)
![image](https://github.com/rusefi/rusefi/assets/15104768/a5aa152d-498b-44e2-a9fd-26aa2c7f8c60)

- STLink-V3MODS
 ![image](https://github.com/rusefi/rusefi/assets/15104768/b51641ad-9f9d-4f95-b8f5-b430d1e6786d)
   * The pinout is:
  Pin 8: GND
  Pin 9: Bridge CAN RX (Input)
  Pin 10: Bridge CAN TX (Output)
  Pin 22: 5V (used for CAN transceiver module power supply)
   * See https://www.st.com/resource/en/user_manual/um2502-stlinkv3mods-and-stlinkv3mini-debuggerprogrammer-tiny-probes-for-stm32-microcontrollers-stmicroelectronics.pdf )

- CAN transceiver module based on MCP2551
![image](https://github.com/rusefi/rusefi/assets/15104768/eb4116c4-676c-4553-9c7a-39dff10839dd)

- STM32CubeProgrammer v2.15.0 (Win64)

Since the bootloader uses only specific pins PB5 (Rx) and PB13 (Tx) for CAN2, and on 2chan we use pins PB12 (SPI2_CS) PB13 (SPI2_SCK), I had to modify the 2chan board by cutting the CAN-RX trace and connecting it with wire to SPI1_MOSI (PB5). The CAN-Tx was already connected correctly. Also, the transceiver in the CAN2 module was not soldered on the board - I had to solder it.

![image](https://github.com/rusefi/rusefi/assets/15104768/0fddb6e1-3163-4f7b-9254-6d122ee24f75)
![image](https://github.com/rusefi/rusefi/assets/15104768/a2824c47-b800-454c-bde3-0e3d9c541f8c)
![image](https://github.com/rusefi/rusefi/assets/15104768/b9aa12e7-77a0-4af6-a01a-f13ca506dd28)

The settings for the STM32CubeProgrammer were used by default, with the exception of the bitrate, which according to AN3154 should be 125kbps.

![image](https://github.com/rusefi/rusefi/assets/15104768/881bcbc9-230f-4722-847f-649d9cb93413)

The data is sent via the CAN bus to the transceiver and to the STM32 (checked with an oscilloscope on pin PB5), and the MCU does not produce anything in response.

![image](https://github.com/rusefi/rusefi/assets/15104768/a9ad7d1a-1291-426f-9a00-357685f0bcf5)

I have a hypothesis that this may be related to the quartz frequency. The AN3154 has the following operating algorithm for the CAN bootloader (Figure 2):

![image](https://github.com/rusefi/rusefi/assets/15104768/7fde3b86-060e-4873-9025-20afab11d165)

It can be seen that they proceed from the assumption that the frequency of the external quartz is either 8 MHz, or 25 MHz, or 14.7456 MHz, and set the bitrate based on this. We have 20 MHz quartz in our mcu module... I can’t check this yet, because I don’t have quartz in the right package for these frequencies...

**Comment by andreika-git** [comment]
It works!

Connected to CAN2 (PB5+PB13) the same way as for the ST bootloader (see #5882):
![image](https://github.com/rusefi/rusefi/assets/15104768/7d687248-2e11-47d5-9ea6-2c22f298f1c5)

It requires some modifications to our openblt code (PR is getting ready). Also we need to somehow switch to "OpenBLT mode" (I used a USB connection and corresponding Console menu option for the switch).
The command line is as following:
```
BootCommander.exe -t=xcp_can -d=peak_pcanusb -c=0 -b=500000 -tid=667h -rid=7E1h rusefi_update.srec
```
The output is:
![image](https://github.com/rusefi/rusefi/assets/15104768/a92f2d68-12bc-454f-a4fc-74e9ea97f669)

**Comment by rusefillc** [comment]
TODO
1. get working on proteus - PR into master if needed
2. get working on small can board - PR into master if needed. I assume there is little change of flash shortage here?

**Comment by andreika-git** [comment]
@rusefillc On small can board, do we need OpenBLT on CAN1 or CAN2?

**Comment by rusefillc** [comment]
@andreika-git can1? But really whichever we can get working with least effort

**Comment by andreika-git** [comment]
OpenBLT+CAN works on small-can-board (CAN1)!
We'll need to re-test it when the next official fw bundle will be ready for the small-can-board.

**Comment by andreika-git** [comment]
Confirmed IT WORKS! with official GHA bundle on small-can-board (https://github.com/rusefi/rusefi/actions/runs/8250061030/artifacts/1318759510)

**Comment by rusefillc** [comment]
Worked in NJ using master!

* manually switch to BLT mode (which needs nicer red blinking on small-can-board @andreika-git )

![image](https://github.com/rusefi/rusefi/assets/48498823/ab8001b9-ed02-4085-8c54-d682cfc058a1)
