### ISSUE TITLE
 a way to build older custom firmware, I guess a step towards custom LTS

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6114]
* say master is broken
* say one day in the future I want to build https://github.com/rusefi/fw-custom-paralela/ from the past

here's the problem:
https://github.com/rusefi/fw-custom-paralela/blob/master/.github/workflows/build-firmware.yaml points at rusefi/rusefi/.github/workflows/custom-board-build.yaml@ *master*

ideally we shall use file system workflow from the submodule we've checked out?

**Comment by rusefillc** [comment]
@chuckwagoncomputing is this something you can help with?

**Comment by chuckwagoncomputing** [comment]
I thought this could be done by having a job that runs first that gets the ref of the submodule.
However, this doesn't work.
```
Invalid workflow file: .github/workflows/build-firmware.yaml#L30
error parsing called workflow
".github/workflows/build-firmware.yaml"
-> "rusefi/rusefi/.github/workflows/custom-board-build.yaml@${{needs.set-ref.outputs.ref}}"
: failed to fetch workflow: reference to workflow should be either a valid branch, tag, or commit
```

Option B is to turn custom_board_build.yaml into an action rather than a workflow, then checkout the submodule in build_firmware.yaml and call the action locally, i.e. `uses: ./ext/rusefi/.github/workflows/custom_board_build.yaml`.
I think this will work but I haven't tried it. It will require updating every custom board repo's build_firmware.yaml as it is a breaking change.

**Comment by rusefillc** [comment]
@chuckwagoncomputing breaking change is zero problem since very few custom repos

**Comment by chuckwagoncomputing** [comment]
Test run: https://github.com/chuckwagoncomputing/fw-custom-example/actions/runs/8157031584
