### ISSUE TITLE
Enable multi core make by default

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#638]
While Eclipse seems to be enabling multi-core compilation, command line "make" still compiles using only one core

Is there any chance to add any magic into the Makefile to compile say using 4 cores by default?

**Comment by rusefi** [comment]
@fpoussin @mck1117 any takers?

**Comment by rusefi** [comment]
https://stackoverflow.com/questions/43367269/why-makeflags-j12-is-not-working-anymore-with-make-4-2

**Comment by mck1117** [comment]
Agree with @fpoussin, I'm not sure it's possible to do only with the makefile.  It's easily possible if you're building from the script or IDE, as those lets you edit the command that's run when it builds.

I misspoke the other day, it turns out it's possible in cmake, but maybe not possible from a regular makefile.

**Comment by mck1117** [comment]
this is done
