### ISSUE TITLE
improve rusefi_updater if two ECUs

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6788]
At the moment rusefi_updater scans for ECUs only once button is clicked
At the moment if two ECUs are connected we are trying to update the first one

Let's improve by showing an error message if two ECUs are connected

**Comment by kifir23917** [comment]
Problematic use cases:
1. connect to USB **ECU#1** in `OpenBlt` mode
2. launch `rusefi_updater` (text on the update button becomes `Blt Update Firmware`)
3. connect to USB **ECU#2** in normal mode (text on the update button becomes `Auto Update Firmware`)
4. press `Auto Update Firmware` button

As result both **ECU#1** and **ECU#2** will be updated.

Another problematic use case:
1. connect to USB **ECU#1** in normal mode
2. launch `rusefi_updater` (text on the update button becomes `Auto Update Firmware`)
3. connect to USB **ECU#2** in normal mode (text on the update button remains `Auto Update Firmware`)
4. press `Auto Update Firmware` button

In the second (when both **ECU#1** and **ECU#2** are in normal mode) the number of updated ECU-s is not determined. If `SerialPortScanner` returns **ECU#2** before **ECU#1**, then both ECU-s will be updated on pressing `Auto Update Firmware` button. Otherwise - only *ECU#1** will be updated.

We need to guarantee that no more than one ECU can be updated on pressing update button.
