### ISSUE TITLE
SD: use min or max MAP within window

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#94]
Currently SD implementation uses average value within the specified crank angle.

It should also be possible to use min or max

Reported by: rusefi

**Comment by OrchardPerformance** [comment]
While the MAX and MIN would seem useful it may actually be a negative. 
The peak depression my not directly relate to the cylinder filling the way the average over the intake stroke would. 
It is possible in some cases of large cams or VVT to observe a sharp peak or dip in the intake trace caused by gas dynamic effects. 
These could maybe fool the ECU to fuel the engine as though it was at a higher or lower load than is reality.

**Comment by mck1117** [comment]
woohoo, map averaging works great!
